name: Publishing

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:
    # Name the Job
    name: Publish as HTML
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Generate HTML
        uses: mgred/asciidoctor-action@master
        with:
            args: asciidoctor index.adoc
